name: QueueTimesMC
version: '${project.version}'
main: fr.mrunicorn.queuetimesmc.QueueTimesMC
api-version: 1.13

depend: [ PlaceholderAPI ]
authors: [ Mr_Unicorn_ ]
description: Real-Time Queue TIme from all your favortie Theme Parks

commands:
  queuetimes:
    description: "QueueTimesMC Command"
    aliases: ["qt"]

permissions:
  queuetimes.*:
    description: "Ability to use all QueueTimesMC commands"

